-- ─────────────────────────────────────────────────────────────────────────────────────────────
--  awto-playwrong crawl — the relational model now lives in code, not here.
-- ─────────────────────────────────────────────────────────────────────────────────────────────
--  `crawl/db.py` defines the schema as SQLAlchemy 2.0 Core Table objects and emits the correct DDL
--  for whichever backend you open (SQLite / Postgres / MySQL) — so there is ONE source of truth and
--  no hand-maintained per-dialect SQL. To create the schema:
--
--      from crawl import db
--      d = db.open_db("site.sqlite")          # or postgresql+psycopg://…  or mysql+pymysql://…
--      d.init_schema()                         # CREATE TABLE … for the backend, idempotent
--
--  To see the exact DDL SQLAlchemy will emit for a backend, without a live DB:
--
--      from sqlalchemy import create_engine
--      from sqlalchemy.schema import CreateTable
--      from crawl.db import _META
--      eng = create_engine("postgresql+psycopg://")      # dialect only, no connection needed
--      for t in _META.sorted_tables:
--          print(CreateTable(t).compile(eng))
--
--  The model (see crawl/db.py for columns + comments):
--    frontier    — the work list + per-URL last-scan status/error code
--    page        — one row per distinct captured page (sha256 identity)
--    page_link   — the page→page reference graph ("what links to what")
--    asset       — one row per distinct fetched image/binary
--    page_asset  — every <img> a page references (image frontier + page↔asset edge)
--    unhandled   — feedback: where the engine fell through to a default (see graph.improvement_report)
--
--  Standardised scan-status vocabulary (a portable CHECK on all backends), from crawl/db.py:
--    ok · empty · nav_timeout · http_error · blocked · render_error · skipped · error
--
--  link_code (on frontier/page/page_asset): an opaque, free-text tag the CONSUMER attaches to a URL
--  (via enqueue(link_code=…)) to join crawled pages/images back to its own domain entity — a resort
--  id, a product SKU, a customer, a site id. The engine never interprets it, so the schema stays
--  domain-agnostic. page also carries text_sha (loose-dup key); page_asset carries caption.
--
--  init_schema() is additive: it creates missing tables AND ALTERs in any column a pre-existing table
--  is missing (never drops/alters existing columns), so a newer engine upgrades an older crawl DB in
--  place with data preserved.
-- ─────────────────────────────────────────────────────────────────────────────────────────────
